- defaults:
    link:
      relink: true
      force: true

- clean: ['~']

- create:
    - ~/.zsh_sessions
    - ~/.config
    - ~/.ssh

- link:
    # Config files
    ~/.config: config

    # Zsh configuration files
    ~/.zlogout: shell/zsh/zlogout
    ~/.zlogin: shell/zsh/zlogin
    ~/.zshenv: shell/zsh/zshenv
    ~/.zprofile: shell/zsh/zprofile
    ~/.zshrc: shell/zsh/zshrc
    ~/.hushlogin: shell/zsh/hushlogin

    # Git configuration files
    ~/.gitconfig: config/git/gitconfig
    ~/.gitconfig.local: config/git/gitconfig.local
    ~/.gitignore_global: config/git/gitignore_global

        # System configuration files
        /opt/homebrew/etc/dnsmasq.conf:
            path: system/dnsmasq/dnsmasq.conf
            if: '[ "$(uname)" = "Darwin" ]'

    # Global EditorConfig file
    ~/.editorconfig: config/.editorconfig

    # Special case: only link ~/.ssh/config if it doesn't already exist
    ~/.ssh/config:
      path: system/ssh/config
      relink: false
      force: false

- shell:
    - [rm -f ~/.bashrc ~/.bash_profile, Removing Bash configuration files]
