[cache]
dir = "~/.cache/tldr"
mirror = "https://github.com/tldr-pages/tldr/releases/latest/download"
auto_update = true
max_age = 336
languages = []

[output]
show_title = true
platform_title = false
show_hyphens = false
example_prefix = "- "
line_length = 0
compact = false
option_style = "long"
raw_markdown = false

[indent]
title = 2
description = 2
bullet = 2
example = 4

[style.title]
color = "#ca9ee6"      # Mauve
background = "default"
bold = true
underline = false
italic = false
dim = false
strikethrough = false

[style.description]
color = "#b5bfe2"      # Subtext1
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

[style.bullet]
color = "#a6d189"      # Green
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

[style.example]
color = "#8caaee"      # Blue
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

[style.url]
color = "#99d1db"      # Sky
background = "default"
bold = false
underline = false
italic = true
dim = false
strikethrough = false

[style.inline_code]
color = "#e5c890"      # Yellow
background = "default"
bold = false
underline = false
italic = true
dim = false
strikethrough = false

[style.placeholder]
color = "#e78284"      # Red
background = "default"
bold = false
underline = false
italic = true
dim = false
strikethrough = false
